### ISSUE TITLE
.query does not respect "values" argument. Options won't work

### ISSUE THREAD

**Issue by killroy42** [steelbrain/mariasql-promise#37]
From the MariaSQL docs:

```
If supplying options without values, you must pass null for values. 
```

**Comment by steelbrain** [comment]
Hey @killroy42, we actually don't support the options parameter in `.query` yet, can you describe your use case? I can add it if you need it

**Comment by killroy42** [comment]
Well, all you need to do is add a null in there ;) I wanted to retrieve the data as an array, for "Show TABLES" use. I've made my own class in the meantime. It's simple enough. Thanks :)

**Comment by steelbrain** [comment]
Open source is amazing 😄 
Glad you did it yourself
