### ISSUE TITLE
utf-8 russian letters

### ISSUE THREAD

**Issue by dcromster** [steelbrain/mariasql-promise#44]
SELECT name FROM streets WHERE name LIKE "Ударников" LIMIT 1;
have no result, but in DB i have 1 street.

Next:
SELECT name FROM streets;
Result:
{ id: '1',
  city_id: '1',
  name: '?????????????? ??????????',
  district_id: '1' }

??? - must be russian letters.

**Comment by steelbrain** [comment]
Hi @dcromster 

You might want to dig through the docs of the original `mariasql`, as this package is just a promise-wrapper around it.

See https://github.com/mscdex/node-mariasql

**Comment by dcromster** [comment]
Thank You!
It works with "charset: 'utf8' " in connection config.
